// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_id, org_id, actor_id, action, target_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, org_id, actor_id, action, target_id, metadata, created_at
`

type InsertAuditLogParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	OrgID    pgtype.UUID `json:"org_id"`
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	TargetID pgtype.UUID `json:"target_id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.ActorID,
		&i.Action,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogByOrg = `-- name: ListAuditLogByOrg :many
SELECT a.id, a.user_id, a.org_id, a.actor_id, a.action, a.target_id, a.metadata, a.created_at, u.username AS actor_username
FROM audit_log a
JOIN users u ON u.id = a.actor_id
WHERE a.org_id = $1
  AND a.created_at < $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAuditLogByOrgParams struct {
	OrgID     pgtype.UUID        `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ListAuditLogByOrgRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	Action        string             `json:"action"`
	TargetID      pgtype.UUID        `json:"target_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername string             `json:"actor_username"`
}

func (q *Queries) ListAuditLogByOrg(ctx context.Context, arg ListAuditLogByOrgParams) ([]ListAuditLogByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByOrg, arg.OrgID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogByOrgRow
	for rows.Next() {
		var i ListAuditLogByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByUser = `-- name: ListAuditLogByUser :many
SELECT a.id, a.user_id, a.org_id, a.actor_id, a.action, a.target_id, a.metadata, a.created_at, u.username AS actor_username
FROM audit_log a
JOIN users u ON u.id = a.actor_id
WHERE a.user_id = $1
  AND a.created_at < $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAuditLogByUserParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

type ListAuditLogByUserRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	ActorID       pgtype.UUID        `json:"actor_id"`
	Action        string             `json:"action"`
	TargetID      pgtype.UUID        `json:"target_id"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorUsername string             `json:"actor_username"`
}

func (q *Queries) ListAuditLogByUser(ctx context.Context, arg ListAuditLogByUserParams) ([]ListAuditLogByUserRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogByUser, arg.UserID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogByUserRow
	for rows.Next() {
		var i ListAuditLogByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
