// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cli_api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCLIAPIKeyForOrg = `-- name: DeleteCLIAPIKeyForOrg :exec
DELETE FROM cli_api_keys WHERE id = $1 AND org_id = $2
`

type DeleteCLIAPIKeyForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteCLIAPIKeyForOrg(ctx context.Context, arg DeleteCLIAPIKeyForOrgParams) error {
	_, err := q.db.Exec(ctx, deleteCLIAPIKeyForOrg, arg.ID, arg.OrgID)
	return err
}

const deleteCLIAPIKeyForUser = `-- name: DeleteCLIAPIKeyForUser :exec
DELETE FROM cli_api_keys WHERE id = $1 AND user_id = $2
`

type DeleteCLIAPIKeyForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteCLIAPIKeyForUser(ctx context.Context, arg DeleteCLIAPIKeyForUserParams) error {
	_, err := q.db.Exec(ctx, deleteCLIAPIKeyForUser, arg.ID, arg.UserID)
	return err
}

const getCLIAPIKeyByHash = `-- name: GetCLIAPIKeyByHash :one
SELECT id, user_id, org_id, key_hash, key_hint, label, created_at FROM cli_api_keys WHERE key_hash = $1
`

func (q *Queries) GetCLIAPIKeyByHash(ctx context.Context, keyHash string) (CliApiKey, error) {
	row := q.db.QueryRow(ctx, getCLIAPIKeyByHash, keyHash)
	var i CliApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const insertCLIAPIKey = `-- name: InsertCLIAPIKey :one
INSERT INTO cli_api_keys (org_id, user_id, key_hash, key_hint, label)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, org_id, key_hash, key_hint, label, created_at
`

type InsertCLIAPIKeyParams struct {
	OrgID   pgtype.UUID `json:"org_id"`
	UserID  pgtype.UUID `json:"user_id"`
	KeyHash string      `json:"key_hash"`
	KeyHint string      `json:"key_hint"`
	Label   string      `json:"label"`
}

func (q *Queries) InsertCLIAPIKey(ctx context.Context, arg InsertCLIAPIKeyParams) (CliApiKey, error) {
	row := q.db.QueryRow(ctx, insertCLIAPIKey,
		arg.OrgID,
		arg.UserID,
		arg.KeyHash,
		arg.KeyHint,
		arg.Label,
	)
	var i CliApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.KeyHash,
		&i.KeyHint,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listCLIAPIKeysByOrg = `-- name: ListCLIAPIKeysByOrg :many
SELECT id, org_id, user_id, key_hint, label, created_at
FROM cli_api_keys
WHERE org_id = $1
ORDER BY created_at DESC
`

type ListCLIAPIKeysByOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	KeyHint   string             `json:"key_hint"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCLIAPIKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListCLIAPIKeysByOrgRow, error) {
	rows, err := q.db.Query(ctx, listCLIAPIKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCLIAPIKeysByOrgRow
	for rows.Next() {
		var i ListCLIAPIKeysByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.KeyHint,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCLIAPIKeysByUser = `-- name: ListCLIAPIKeysByUser :many
SELECT id, org_id, user_id, key_hint, label, created_at
FROM cli_api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListCLIAPIKeysByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	KeyHint   string             `json:"key_hint"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCLIAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ListCLIAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listCLIAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCLIAPIKeysByUserRow
	for rows.Next() {
		var i ListCLIAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.KeyHint,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
