// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContextTokenForOrg = `-- name: DeleteContextTokenForOrg :exec
DELETE FROM context_tokens WHERE id = $1 AND org_id = $2
`

type DeleteContextTokenForOrgParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteContextTokenForOrg(ctx context.Context, arg DeleteContextTokenForOrgParams) error {
	_, err := q.db.Exec(ctx, deleteContextTokenForOrg, arg.ID, arg.OrgID)
	return err
}

const deleteContextTokenForUser = `-- name: DeleteContextTokenForUser :exec
DELETE FROM context_tokens WHERE id = $1 AND user_id = $2
`

type DeleteContextTokenForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteContextTokenForUser(ctx context.Context, arg DeleteContextTokenForUserParams) error {
	_, err := q.db.Exec(ctx, deleteContextTokenForUser, arg.ID, arg.UserID)
	return err
}

const deleteExpiredContextTokens = `-- name: DeleteExpiredContextTokens :exec
DELETE FROM context_tokens WHERE expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredContextTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredContextTokens)
	return err
}

const getContextTokenByHash = `-- name: GetContextTokenByHash :one
SELECT id, repo_id, user_id, org_id, target_snapshot_id, token_hash,
    label, last_used_at, expires_at, visibility, created_at
FROM context_tokens
WHERE token_hash = $1
`

type GetContextTokenByHashRow struct {
	ID               pgtype.UUID        `json:"id"`
	RepoID           pgtype.UUID        `json:"repo_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TargetSnapshotID pgtype.UUID        `json:"target_snapshot_id"`
	TokenHash        string             `json:"token_hash"`
	Label            pgtype.Text        `json:"label"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Visibility       ContextVisibility  `json:"visibility"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetContextTokenByHash(ctx context.Context, tokenHash string) (GetContextTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getContextTokenByHash, tokenHash)
	var i GetContextTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.UserID,
		&i.OrgID,
		&i.TargetSnapshotID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const insertContextToken = `-- name: InsertContextToken :one
INSERT INTO context_tokens (repo_id, user_id, org_id,
target_snapshot_id, token_hash, label, expires_at, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, repo_id, user_id, org_id, target_snapshot_id,
token_hash, label, last_used_at, expires_at, visibility, created_at
`

type InsertContextTokenParams struct {
	RepoID           pgtype.UUID        `json:"repo_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TargetSnapshotID pgtype.UUID        `json:"target_snapshot_id"`
	TokenHash        string             `json:"token_hash"`
	Label            pgtype.Text        `json:"label"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Visibility       ContextVisibility  `json:"visibility"`
}

type InsertContextTokenRow struct {
	ID               pgtype.UUID        `json:"id"`
	RepoID           pgtype.UUID        `json:"repo_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TargetSnapshotID pgtype.UUID        `json:"target_snapshot_id"`
	TokenHash        string             `json:"token_hash"`
	Label            pgtype.Text        `json:"label"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Visibility       ContextVisibility  `json:"visibility"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertContextToken(ctx context.Context, arg InsertContextTokenParams) (InsertContextTokenRow, error) {
	row := q.db.QueryRow(ctx, insertContextToken,
		arg.RepoID,
		arg.UserID,
		arg.OrgID,
		arg.TargetSnapshotID,
		arg.TokenHash,
		arg.Label,
		arg.ExpiresAt,
		arg.Visibility,
	)
	var i InsertContextTokenRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.UserID,
		&i.OrgID,
		&i.TargetSnapshotID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Visibility,
		&i.CreatedAt,
	)
	return i, err
}

const listContextTokensByRepo = `-- name: ListContextTokensByRepo :many
SELECT ct.id, ct.repo_id, ct.user_id, ct.org_id, ct.target_snapshot_id,
    ct.label, ct.last_used_at, ct.expires_at, ct.visibility, ct.created_at,
    (SELECT count(*) FROM context_token_allowed_users WHERE token_id = ct.id)::int AS allowed_user_count
FROM context_tokens ct
WHERE ct.repo_id = $1
ORDER BY ct.created_at DESC
`

type ListContextTokensByRepoRow struct {
	ID               pgtype.UUID        `json:"id"`
	RepoID           pgtype.UUID        `json:"repo_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TargetSnapshotID pgtype.UUID        `json:"target_snapshot_id"`
	Label            pgtype.Text        `json:"label"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Visibility       ContextVisibility  `json:"visibility"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AllowedUserCount int32              `json:"allowed_user_count"`
}

func (q *Queries) ListContextTokensByRepo(ctx context.Context, repoID pgtype.UUID) ([]ListContextTokensByRepoRow, error) {
	rows, err := q.db.Query(ctx, listContextTokensByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextTokensByRepoRow
	for rows.Next() {
		var i ListContextTokensByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.UserID,
			&i.OrgID,
			&i.TargetSnapshotID,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.Visibility,
			&i.CreatedAt,
			&i.AllowedUserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContextTokenLastUsed = `-- name: UpdateContextTokenLastUsed :exec
UPDATE context_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateContextTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateContextTokenLastUsed, id)
	return err
}
