// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_token_allowed_users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContextTokenAllowedUser = `-- name: DeleteContextTokenAllowedUser :exec
DELETE FROM context_token_allowed_users
WHERE token_id = $1 AND user_id = $2
`

type DeleteContextTokenAllowedUserParams struct {
	TokenID pgtype.UUID `json:"token_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteContextTokenAllowedUser(ctx context.Context, arg DeleteContextTokenAllowedUserParams) error {
	_, err := q.db.Exec(ctx, deleteContextTokenAllowedUser, arg.TokenID, arg.UserID)
	return err
}

const insertContextTokenAllowedUser = `-- name: InsertContextTokenAllowedUser :exec
INSERT INTO context_token_allowed_users (token_id, user_id)
VALUES ($1, $2)
ON CONFLICT (token_id, user_id) DO NOTHING
`

type InsertContextTokenAllowedUserParams struct {
	TokenID pgtype.UUID `json:"token_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) InsertContextTokenAllowedUser(ctx context.Context, arg InsertContextTokenAllowedUserParams) error {
	_, err := q.db.Exec(ctx, insertContextTokenAllowedUser, arg.TokenID, arg.UserID)
	return err
}

const isUserAllowedForToken = `-- name: IsUserAllowedForToken :one
SELECT EXISTS (
    SELECT 1 FROM context_token_allowed_users
    WHERE token_id = $1 AND user_id = $2
) AS allowed
`

type IsUserAllowedForTokenParams struct {
	TokenID pgtype.UUID `json:"token_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsUserAllowedForToken(ctx context.Context, arg IsUserAllowedForTokenParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAllowedForToken, arg.TokenID, arg.UserID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listContextTokenAllowedUsers = `-- name: ListContextTokenAllowedUsers :many
SELECT ctau.id, ctau.user_id, u.username, u.email, ctau.created_at
FROM context_token_allowed_users ctau
JOIN users u ON u.id = ctau.user_id
WHERE ctau.token_id = $1
ORDER BY ctau.created_at DESC
`

type ListContextTokenAllowedUsersRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListContextTokenAllowedUsers(ctx context.Context, tokenID pgtype.UUID) ([]ListContextTokenAllowedUsersRow, error) {
	rows, err := q.db.Query(ctx, listContextTokenAllowedUsers, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextTokenAllowedUsersRow
	for rows.Next() {
		var i ListContextTokenAllowedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceContextTokenAllowedUsers = `-- name: ReplaceContextTokenAllowedUsers :exec
DELETE FROM context_token_allowed_users WHERE token_id = $1
`

func (q *Queries) ReplaceContextTokenAllowedUsers(ctx context.Context, tokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceContextTokenAllowedUsers, tokenID)
	return err
}
