// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMembershipsByOrg = `-- name: CountMembershipsByOrg :one
SELECT count(*) FROM memberships WHERE org_id = $1
`

func (q *Queries) CountMembershipsByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnersByOrg = `-- name: CountOwnersByOrg :one
SELECT count(*) FROM memberships WHERE org_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnersByOrg(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, org_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, org_id, role, invited_by, joined_at
`

type CreateMembershipParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	OrgID     pgtype.UUID `json:"org_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.UserID,
		arg.OrgID,
		arg.Role,
		arg.InvitedBy,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE user_id = $1 AND org_id = $2
`

type DeleteMembershipParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.OrgID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, org_id, role, invited_by, joined_at FROM memberships WHERE user_id = $1 AND org_id = $2
`

type GetMembershipParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OrgID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const listMembershipsByOrg = `-- name: ListMembershipsByOrg :many
SELECT m.id, m.user_id, m.org_id, m.role, m.invited_by, m.joined_at, u.username, u.email, u.avatar_url
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.joined_at ASC
`

type ListMembershipsByOrgRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Role      string             `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListMembershipsByOrg(ctx context.Context, orgID pgtype.UUID) ([]ListMembershipsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByOrgRow
	for rows.Next() {
		var i ListMembershipsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.id, m.user_id, m.org_id, m.role, m.invited_by, m.joined_at, o.slug AS org_slug, o.name AS org_name
FROM memberships m
JOIN organizations o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY m.joined_at ASC
`

type ListMembershipsByUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Role      string             `json:"role"`
	InvitedBy pgtype.UUID        `json:"invited_by"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	OrgSlug   string             `json:"org_slug"`
	OrgName   string             `json:"org_name"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID pgtype.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserRow
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.OrgSlug,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships SET role = $3
WHERE user_id = $1 AND org_id = $2
RETURNING id, user_id, org_id, role, invited_by, joined_at
`

type UpdateMembershipRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	OrgID  pgtype.UUID `json:"org_id"`
	Role   string      `json:"role"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.UserID, arg.OrgID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}
