// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AiProviderKey struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	Provider  string
	KeyCipher []byte
	KeyHint   string
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.UUID
}

type AuditLog struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OrgID     pgtype.UUID
	ActorID   pgtype.UUID
	Action    string
	TargetID  pgtype.UUID
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type CliApiKey struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OrgID     pgtype.UUID
	KeyHash   string
	KeyHint   string
	Label     string
	CreatedAt pgtype.Timestamptz
}

type ContextToken struct {
	ID               pgtype.UUID
	RepoID           pgtype.UUID
	OrgID            pgtype.UUID
	TargetSnapshotID pgtype.UUID
	TokenHash        string
	Label            pgtype.Text
	LastUsedAt       pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UserID           pgtype.UUID
}

type Job struct {
	ID           pgtype.UUID
	RepoID       pgtype.UUID
	Branch       string
	CommitSha    string
	DeliveryID   pgtype.Text
	Status       JobStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type Membership struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OrgID     pgtype.UUID
	Role      string
	InvitedBy pgtype.UUID
	JoinedAt  pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
	AuthOrgID string
}

type Repository struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	GithubRepoID   int64
	InstallationID int64
	FullName       string
	DefaultBranch  string
	InstalledAt    pgtype.Timestamptz
	UserID         pgtype.UUID
}

type Session struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	AuthSessionID string
	DeviceName    pgtype.Text
	IpAddress     *netip.Addr
	LastActiveAt  pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Snapshot struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	JobID           pgtype.UUID
	Branch          string
	CommitSha       string
	GcsPath         string
	SnapshotVersion int32
	ZigzagVersion   string
	SizeBytes       int64
	CreatedAt       pgtype.Timestamptz
	Metadata        []byte
}

type User struct {
	ID            pgtype.UUID
	AuthUserID    string
	Username      string
	Email         string
	EmailVerified bool
	Phone         pgtype.Text
	AvatarUrl     pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
