// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrgByAuthID = `-- name: GetOrgByAuthID :one
SELECT id, slug, name, created_at, auth_org_id FROM organizations WHERE auth_org_id = $1
`

func (q *Queries) GetOrgByAuthID(ctx context.Context, authOrgID string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByAuthID, authOrgID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.AuthOrgID,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, created_at, auth_org_id FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.AuthOrgID,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, created_at, auth_org_id FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.AuthOrgID,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations SET name = $2, slug = $3
WHERE id = $1
RETURNING id, slug, name, created_at, auth_org_id
`

type UpdateOrganizationParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Slug string      `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.AuthOrgID,
	)
	return i, err
}

const upsertOrg = `-- name: UpsertOrg :one
INSERT INTO organizations (auth_org_id, slug, name)
VALUES ($1, $2, $3)
ON CONFLICT (auth_org_id) DO UPDATE
    SET name = EXCLUDED.name
RETURNING id, slug, name, created_at, auth_org_id
`

type UpsertOrgParams struct {
	AuthOrgID string `json:"auth_org_id"`
	Slug      string `json:"slug"`
	Name      string `json:"name"`
}

func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, upsertOrg, arg.AuthOrgID, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.AuthOrgID,
	)
	return i, err
}
