// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoByFullNameAndOrg = `-- name: GetRepoByFullNameAndOrg :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories WHERE full_name = $1 AND org_id = $2
`

type GetRepoByFullNameAndOrgParams struct {
	FullName string      `json:"full_name"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetRepoByFullNameAndOrg(ctx context.Context, arg GetRepoByFullNameAndOrgParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByFullNameAndOrg, arg.FullName, arg.OrgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
		&i.UserID,
	)
	return i, err
}

const getRepoByFullNameAndUser = `-- name: GetRepoByFullNameAndUser :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories WHERE full_name = $1 AND user_id = $2
`

type GetRepoByFullNameAndUserParams struct {
	FullName string      `json:"full_name"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRepoByFullNameAndUser(ctx context.Context, arg GetRepoByFullNameAndUserParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByFullNameAndUser, arg.FullName, arg.UserID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
		&i.UserID,
	)
	return i, err
}

const getRepoByGithubID = `-- name: GetRepoByGithubID :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories WHERE github_repo_id = $1
`

func (q *Queries) GetRepoByGithubID(ctx context.Context, githubRepoID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByGithubID, githubRepoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
		&i.UserID,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
		&i.UserID,
	)
	return i, err
}

const listReposByOrg = `-- name: ListReposByOrg :many
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories
WHERE org_id = $1
  AND full_name > $2
ORDER BY full_name ASC
LIMIT $3
`

type ListReposByOrgParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	FullName string      `json:"full_name"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListReposByOrg(ctx context.Context, arg ListReposByOrgParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listReposByOrg, arg.OrgID, arg.FullName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GithubRepoID,
			&i.InstallationID,
			&i.FullName,
			&i.DefaultBranch,
			&i.InstalledAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByUser = `-- name: ListReposByUser :many
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id FROM repositories
WHERE user_id = $1
  AND full_name > $2
ORDER BY full_name ASC
LIMIT $3
`

type ListReposByUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FullName string      `json:"full_name"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListReposByUser(ctx context.Context, arg ListReposByUserParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listReposByUser, arg.UserID, arg.FullName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GithubRepoID,
			&i.InstallationID,
			&i.FullName,
			&i.DefaultBranch,
			&i.InstalledAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repositories (user_id, org_id, github_repo_id, installation_id, full_name, default_branch)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (github_repo_id) DO UPDATE
    SET installation_id = EXCLUDED.installation_id,
        full_name       = EXCLUDED.full_name,
        default_branch  = EXCLUDED.default_branch
RETURNING id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at, user_id
`

type UpsertRepoParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrgID          pgtype.UUID `json:"org_id"`
	GithubRepoID   int64       `json:"github_repo_id"`
	InstallationID int64       `json:"installation_id"`
	FullName       string      `json:"full_name"`
	DefaultBranch  string      `json:"default_branch"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.UserID,
		arg.OrgID,
		arg.GithubRepoID,
		arg.InstallationID,
		arg.FullName,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
		&i.UserID,
	)
	return i, err
}
