// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllSessionsByUser = `-- name: DeleteAllSessionsByUser :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteAllSessionsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllSessionsByUser, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	return err
}

const deleteSessionByAuthID = `-- name: DeleteSessionByAuthID :exec
DELETE FROM sessions WHERE auth_session_id = $1
`

func (q *Queries) DeleteSessionByAuthID(ctx context.Context, authSessionID string) error {
	_, err := q.db.Exec(ctx, deleteSessionByAuthID, authSessionID)
	return err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, auth_session_id, device_name, ip_address, last_active_at, created_at FROM sessions
WHERE user_id = $1
ORDER BY last_active_at DESC
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthSessionID,
			&i.DeviceName,
			&i.IpAddress,
			&i.LastActiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (user_id, auth_session_id, device_name, ip_address)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth_session_id) DO UPDATE
    SET last_active_at = now(),
        device_name    = EXCLUDED.device_name,
        ip_address     = EXCLUDED.ip_address
RETURNING id, user_id, auth_session_id, device_name, ip_address, last_active_at, created_at
`

type UpsertSessionParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	AuthSessionID string      `json:"auth_session_id"`
	DeviceName    pgtype.Text `json:"device_name"`
	IpAddress     *netip.Addr `json:"ip_address"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.UserID,
		arg.AuthSessionID,
		arg.DeviceName,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthSessionID,
		&i.DeviceName,
		&i.IpAddress,
		&i.LastActiveAt,
		&i.CreatedAt,
	)
	return i, err
}
