// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE auth_user_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthID, authUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username       = COALESCE(NULLIF($1::text, ''), username),
    email          = COALESCE(NULLIF($2::text, ''), email),
    email_verified = $3,
    phone          = $4,
    avatar_url     = $5
WHERE id = $6
RETURNING id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	Phone         pgtype.Text `json:"phone"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (auth_user_id, username, email, email_verified, phone, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (auth_user_id) DO UPDATE
    SET username       = EXCLUDED.username,
        email          = EXCLUDED.email,
        email_verified = EXCLUDED.email_verified,
        phone          = EXCLUDED.phone,
        avatar_url     = EXCLUDED.avatar_url
RETURNING id, auth_user_id, username, email, email_verified, phone, avatar_url, created_at, updated_at
`

type UpsertUserParams struct {
	AuthUserID    string      `json:"auth_user_id"`
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	Phone         pgtype.Text `json:"phone"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.AuthUserID,
		arg.Username,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.Phone,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
