// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (repo_id, branch, commit_sha, delivery_id)
VALUES ($1, $2, $3, NULLIF($4, ''))
RETURNING id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	RepoID    pgtype.UUID
	Branch    string
	CommitSha string
	Column4   interface{}
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.RepoID,
		arg.Branch,
		arg.CommitSha,
		arg.Column4,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveJobsForBranch = `-- name: GetActiveJobsForBranch :many
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs
WHERE repo_id = $1
  AND branch = $2
  AND status IN ('queued', 'running')
ORDER BY created_at ASC
`

type GetActiveJobsForBranchParams struct {
	RepoID pgtype.UUID
	Branch string
}

func (q *Queries) GetActiveJobsForBranch(ctx context.Context, arg GetActiveJobsForBranchParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, getActiveJobsForBranch, arg.RepoID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Branch,
			&i.CommitSha,
			&i.DeliveryID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobsByRepo = `-- name: ListJobsByRepo :many
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs
WHERE repo_id = $1
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListJobsByRepoParams struct {
	RepoID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListJobsByRepo(ctx context.Context, arg ListJobsByRepoParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRepo, arg.RepoID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Branch,
			&i.CommitSha,
			&i.DeliveryID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobSuperseded = `-- name: MarkJobSuperseded :exec
UPDATE jobs
SET status = 'superseded'
WHERE id = $1
  AND status = 'queued'
`

func (q *Queries) MarkJobSuperseded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobSuperseded, id)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2,
    error_message = $3,
    started_at    = CASE WHEN $2 = 'running' THEN now() ELSE started_at END,
    finished_at   = CASE WHEN $2 IN ('succeeded', 'failed', 'cancelled', 'superseded') THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID           pgtype.UUID
	Status       JobStatus
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
