// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoByGithubID = `-- name: GetRepoByGithubID :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at FROM repositories WHERE github_repo_id = $1
`

func (q *Queries) GetRepoByGithubID(ctx context.Context, githubRepoID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByGithubID, githubRepoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repositories (org_id, github_repo_id, installation_id, full_name, default_branch)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (github_repo_id) DO UPDATE
    SET installation_id = EXCLUDED.installation_id,
        full_name       = EXCLUDED.full_name,
        default_branch  = EXCLUDED.default_branch
RETURNING id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at
`

type UpsertRepoParams struct {
	OrgID          pgtype.UUID
	GithubRepoID   int64
	InstallationID int64
	FullName       string
	DefaultBranch  string
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.OrgID,
		arg.GithubRepoID,
		arg.InstallationID,
		arg.FullName,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}
