// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_provider_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIProviderKey = `-- name: DeleteAIProviderKey :exec
DELETE FROM ai_provider_keys WHERE org_id = $1 AND provider = $2
`

type DeleteAIProviderKeyParams struct {
	OrgID    pgtype.UUID
	Provider string
}

func (q *Queries) DeleteAIProviderKey(ctx context.Context, arg DeleteAIProviderKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAIProviderKey, arg.OrgID, arg.Provider)
	return err
}

const getAIProviderKey = `-- name: GetAIProviderKey :one
SELECT id, org_id, provider, key_cipher, key_hint, created_at
FROM ai_provider_keys
WHERE org_id = $1 AND provider = $2
`

type GetAIProviderKeyParams struct {
	OrgID    pgtype.UUID
	Provider string
}

func (q *Queries) GetAIProviderKey(ctx context.Context, arg GetAIProviderKeyParams) (AiProviderKey, error) {
	row := q.db.QueryRow(ctx, getAIProviderKey, arg.OrgID, arg.Provider)
	var i AiProviderKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.KeyCipher,
		&i.KeyHint,
		&i.CreatedAt,
	)
	return i, err
}

const listAIProviderKeys = `-- name: ListAIProviderKeys :many
SELECT id, org_id, provider, key_hint, created_at
FROM ai_provider_keys
WHERE org_id = $1
ORDER BY provider ASC
`

type ListAIProviderKeysRow struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	Provider  string
	KeyHint   string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAIProviderKeys(ctx context.Context, orgID pgtype.UUID) ([]ListAIProviderKeysRow, error) {
	rows, err := q.db.Query(ctx, listAIProviderKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIProviderKeysRow
	for rows.Next() {
		var i ListAIProviderKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Provider,
			&i.KeyHint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAIProviderKey = `-- name: UpsertAIProviderKey :one
INSERT INTO ai_provider_keys (org_id, provider, key_cipher, key_hint)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, provider) DO UPDATE
    SET key_cipher = EXCLUDED.key_cipher,
    key_hint = EXCLUDED.key_hint
RETURNING id, org_id, provider, key_cipher, key_hint,
created_at
`

type UpsertAIProviderKeyParams struct {
	OrgID     pgtype.UUID
	Provider  string
	KeyCipher []byte
	KeyHint   string
}

func (q *Queries) UpsertAIProviderKey(ctx context.Context, arg UpsertAIProviderKeyParams) (AiProviderKey, error) {
	row := q.db.QueryRow(ctx, upsertAIProviderKey,
		arg.OrgID,
		arg.Provider,
		arg.KeyCipher,
		arg.KeyHint,
	)
	var i AiProviderKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.KeyCipher,
		&i.KeyHint,
		&i.CreatedAt,
	)
	return i, err
}
