// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteContextToken = `-- name: DeleteContextToken :exec
DELETE FROM context_tokens WHERE id = $1 AND org_id = $2
`

type DeleteContextTokenParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) DeleteContextToken(ctx context.Context, arg DeleteContextTokenParams) error {
	_, err := q.db.Exec(ctx, deleteContextToken, arg.ID, arg.OrgID)
	return err
}

const deleteExpiredContextTokens = `-- name: DeleteExpiredContextTokens :exec
DELETE FROM context_tokens WHERE expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredContextTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredContextTokens)
	return err
}

const getContextTokenByHash = `-- name: GetContextTokenByHash :one
SELECT id, repo_id, org_id, target_snapshot_id, token_hash,
    label, last_used_at, expires_at, created_at
FROM context_tokens
WHERE token_hash = $1
`

func (q *Queries) GetContextTokenByHash(ctx context.Context, tokenHash string) (ContextToken, error) {
	row := q.db.QueryRow(ctx, getContextTokenByHash, tokenHash)
	var i ContextToken
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.OrgID,
		&i.TargetSnapshotID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertContextToken = `-- name: InsertContextToken :one
INSERT INTO context_tokens (repo_id, org_id,
target_snapshot_id, token_hash, label, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo_id, org_id, target_snapshot_id,
token_hash, label, last_used_at, expires_at, created_at
`

type InsertContextTokenParams struct {
	RepoID           pgtype.UUID
	OrgID            pgtype.UUID
	TargetSnapshotID pgtype.UUID
	TokenHash        string
	Label            pgtype.Text
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) InsertContextToken(ctx context.Context, arg InsertContextTokenParams) (ContextToken, error) {
	row := q.db.QueryRow(ctx, insertContextToken,
		arg.RepoID,
		arg.OrgID,
		arg.TargetSnapshotID,
		arg.TokenHash,
		arg.Label,
		arg.ExpiresAt,
	)
	var i ContextToken
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.OrgID,
		&i.TargetSnapshotID,
		&i.TokenHash,
		&i.Label,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listContextTokensByRepo = `-- name: ListContextTokensByRepo :many
SELECT id, repo_id, org_id, target_snapshot_id, label,
    last_used_at, expires_at, created_at
FROM context_tokens
WHERE repo_id = $1
ORDER BY created_at DESC
`

type ListContextTokensByRepoRow struct {
	ID               pgtype.UUID
	RepoID           pgtype.UUID
	OrgID            pgtype.UUID
	TargetSnapshotID pgtype.UUID
	Label            pgtype.Text
	LastUsedAt       pgtype.Timestamptz
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListContextTokensByRepo(ctx context.Context, repoID pgtype.UUID) ([]ListContextTokensByRepoRow, error) {
	rows, err := q.db.Query(ctx, listContextTokensByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextTokensByRepoRow
	for rows.Next() {
		var i ListContextTokensByRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.OrgID,
			&i.TargetSnapshotID,
			&i.Label,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContextTokenLastUsed = `-- name: UpdateContextTokenLastUsed :exec
UPDATE context_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateContextTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateContextTokenLastUsed, id)
	return err
}
