// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', started_at = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'queued'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at
`

func (q *Queries) ClaimJob(ctx context.Context) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (repo_id, branch, commit_sha, delivery_id)
VALUES ($1, $2, $3, NULLIF($4, ''))
RETURNING id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	RepoID    pgtype.UUID
	Branch    string
	CommitSha string
	Column4   interface{}
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.RepoID,
		arg.Branch,
		arg.CommitSha,
		arg.Column4,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getActiveJobsForBranch = `-- name: GetActiveJobsForBranch :many
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs
WHERE repo_id = $1
  AND branch = $2
  AND status IN ('queued', 'running')
ORDER BY created_at ASC
`

type GetActiveJobsForBranchParams struct {
	RepoID pgtype.UUID
	Branch string
}

func (q *Queries) GetActiveJobsForBranch(ctx context.Context, arg GetActiveJobsForBranchParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, getActiveJobsForBranch, arg.RepoID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Branch,
			&i.CommitSha,
			&i.DeliveryID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJobForUpdate = `-- name: GetJobForUpdate :one
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetJobForUpdate(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobForUpdate, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Branch,
		&i.CommitSha,
		&i.DeliveryID,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRepoForJob = `-- name: GetRepoForJob :one
SELECT r.id, r.github_repo_id, r.installation_id, r.full_name, r.default_branch
FROM repositories r
JOIN jobs j ON j.repo_id = r.id
WHERE j.id = $1
`

type GetRepoForJobRow struct {
	ID             pgtype.UUID
	GithubRepoID   int64
	InstallationID int64
	FullName       string
	DefaultBranch  string
}

func (q *Queries) GetRepoForJob(ctx context.Context, id pgtype.UUID) (GetRepoForJobRow, error) {
	row := q.db.QueryRow(ctx, getRepoForJob, id)
	var i GetRepoForJobRow
	err := row.Scan(
		&i.ID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
	)
	return i, err
}

const listJobsByRepo = `-- name: ListJobsByRepo :many
SELECT id, repo_id, branch, commit_sha, delivery_id, status, error_message, created_at, updated_at, started_at, finished_at FROM jobs
WHERE repo_id = $1
  AND created_at < $2
ORDER BY created_at DESC
LIMIT $3
`

type ListJobsByRepoParams struct {
	RepoID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	Limit     int32
}

func (q *Queries) ListJobsByRepo(ctx context.Context, arg ListJobsByRepoParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRepo, arg.RepoID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.Branch,
			&i.CommitSha,
			&i.DeliveryID,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobSuperseded = `-- name: MarkJobSuperseded :exec
UPDATE jobs
SET status = 'superseded'
WHERE id = $1
  AND status = 'queued'
`

func (q *Queries) MarkJobSuperseded(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobSuperseded, id)
	return err
}

const timeoutRunningJobs = `-- name: TimeoutRunningJobs :execrows
UPDATE jobs
SET status = 'failed',
    error_message = 'Job timed out',
    finished_at = now()
WHERE status = 'running'
  AND started_at < now() - make_interval(mins => $1::int)
`

func (q *Queries) TimeoutRunningJobs(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, timeoutRunningJobs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateJobCommitSHA = `-- name: UpdateJobCommitSHA :exec
UPDATE jobs SET commit_sha = $2 WHERE id = $1 AND status = 'queued'
`

type UpdateJobCommitSHAParams struct {
	ID        pgtype.UUID
	CommitSha string
}

func (q *Queries) UpdateJobCommitSHA(ctx context.Context, arg UpdateJobCommitSHAParams) error {
	_, err := q.db.Exec(ctx, updateJobCommitSHA, arg.ID, arg.CommitSha)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = $2,
    error_message = $3,
    started_at    = CASE WHEN $2 = 'running' THEN now() ELSE started_at END,
    finished_at   = CASE WHEN $2 IN ('succeeded', 'failed', 'cancelled', 'superseded') THEN now() ELSE finished_at END
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID           pgtype.UUID
	Status       JobStatus
	ErrorMessage pgtype.Text
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
