// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID           pgtype.UUID
	RepoID       pgtype.UUID
	Branch       string
	CommitSha    string
	DeliveryID   pgtype.Text
	Status       JobStatus
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
}

type Organization struct {
	ID         pgtype.UUID
	ClerkOrgID string
	Slug       string
	Name       string
	CreatedAt  pgtype.Timestamptz
}

type Repository struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	GithubRepoID   int64
	InstallationID int64
	FullName       string
	DefaultBranch  string
	InstalledAt    pgtype.Timestamptz
}

type Snapshot struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	JobID           pgtype.UUID
	Branch          string
	CommitSha       string
	GcsPath         string
	SnapshotVersion int32
	ZigzagVersion   string
	SizeBytes       int64
	CreatedAt       pgtype.Timestamptz
}
