// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package store

import (
	"context"
)

const getOrgByClerkID = `-- name: GetOrgByClerkID :one
SELECT id, clerk_org_id, slug, name, created_at FROM organizations WHERE clerk_org_id = $1
`

func (q *Queries) GetOrgByClerkID(ctx context.Context, clerkOrgID string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByClerkID, clerkOrgID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, clerk_org_id, slug, name, created_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOrg = `-- name: UpsertOrg :one
INSERT INTO organizations (clerk_org_id, slug, name)
VALUES ($1, $2, $3)
ON CONFLICT (clerk_org_id) DO UPDATE
    SET name = EXCLUDED.name
RETURNING id, clerk_org_id, slug, name, created_at
`

type UpsertOrgParams struct {
	ClerkOrgID string
	Slug       string
	Name       string
}

func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, upsertOrg, arg.ClerkOrgID, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.ClerkOrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
