// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoByFullNameAndOrg = `-- name: GetRepoByFullNameAndOrg :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at FROM repositories WHERE full_name = $1 AND org_id = $2
`

type GetRepoByFullNameAndOrgParams struct {
	FullName string
	OrgID    pgtype.UUID
}

func (q *Queries) GetRepoByFullNameAndOrg(ctx context.Context, arg GetRepoByFullNameAndOrgParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByFullNameAndOrg, arg.FullName, arg.OrgID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}

const getRepoByGithubID = `-- name: GetRepoByGithubID :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at FROM repositories WHERE github_repo_id = $1
`

func (q *Queries) GetRepoByGithubID(ctx context.Context, githubRepoID int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByGithubID, githubRepoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}

const getRepoByID = `-- name: GetRepoByID :one
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepoByID(ctx context.Context, id pgtype.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepoByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}

const listReposByOrg = `-- name: ListReposByOrg :many
SELECT id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at FROM repositories
WHERE org_id = $1
  AND full_name > $2
ORDER BY full_name ASC
LIMIT $3
`

type ListReposByOrgParams struct {
	OrgID    pgtype.UUID
	FullName string
	Limit    int32
}

func (q *Queries) ListReposByOrg(ctx context.Context, arg ListReposByOrgParams) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listReposByOrg, arg.OrgID, arg.FullName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GithubRepoID,
			&i.InstallationID,
			&i.FullName,
			&i.DefaultBranch,
			&i.InstalledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repositories (org_id, github_repo_id, installation_id, full_name, default_branch)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (github_repo_id) DO UPDATE
    SET installation_id = EXCLUDED.installation_id,
        full_name       = EXCLUDED.full_name,
        default_branch  = EXCLUDED.default_branch
RETURNING id, org_id, github_repo_id, installation_id, full_name, default_branch, installed_at
`

type UpsertRepoParams struct {
	OrgID          pgtype.UUID
	GithubRepoID   int64
	InstallationID int64
	FullName       string
	DefaultBranch  string
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.OrgID,
		arg.GithubRepoID,
		arg.InstallationID,
		arg.FullName,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GithubRepoID,
		&i.InstallationID,
		&i.FullName,
		&i.DefaultBranch,
		&i.InstalledAt,
	)
	return i, err
}
