// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSnapshot = `-- name: GetLatestSnapshot :one
SELECT id, repo_id, job_id, branch, commit_sha, gcs_path, snapshot_version, zigzag_version, size_bytes, created_at, metadata FROM snapshots
WHERE repo_id = $1 AND branch = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestSnapshotParams struct {
	RepoID pgtype.UUID
	Branch string
}

func (q *Queries) GetLatestSnapshot(ctx context.Context, arg GetLatestSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshot, arg.RepoID, arg.Branch)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.JobID,
		&i.Branch,
		&i.CommitSha,
		&i.GcsPath,
		&i.SnapshotVersion,
		&i.ZigzagVersion,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getSnapshotByID = `-- name: GetSnapshotByID :one
SELECT id, repo_id, job_id, branch, commit_sha, gcs_path, snapshot_version, zigzag_version, size_bytes, created_at, metadata FROM snapshots WHERE id = $1
`

func (q *Queries) GetSnapshotByID(ctx context.Context, id pgtype.UUID) (Snapshot, error) {
	row := q.db.QueryRow(ctx, getSnapshotByID, id)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.JobID,
		&i.Branch,
		&i.CommitSha,
		&i.GcsPath,
		&i.SnapshotVersion,
		&i.ZigzagVersion,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}

const getSnapshotsByBranch = `-- name: GetSnapshotsByBranch :many
SELECT id, repo_id, job_id, branch, commit_sha, gcs_path, snapshot_version, zigzag_version, size_bytes, created_at, metadata FROM snapshots
WHERE repo_id = $1 AND branch = $2
ORDER BY created_at DESC
`

type GetSnapshotsByBranchParams struct {
	RepoID pgtype.UUID
	Branch string
}

func (q *Queries) GetSnapshotsByBranch(ctx context.Context, arg GetSnapshotsByBranchParams) ([]Snapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotsByBranch, arg.RepoID, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.JobID,
			&i.Branch,
			&i.CommitSha,
			&i.GcsPath,
			&i.SnapshotVersion,
			&i.ZigzagVersion,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCLISnapshot = `-- name: InsertCLISnapshot :one
INSERT INTO snapshots (repo_id, branch, commit_sha, gcs_path,
    snapshot_version, zigzag_version, size_bytes, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (repo_id, branch, commit_sha) DO UPDATE
 SET gcs_path = EXCLUDED.gcs_path,
     snapshot_version = EXCLUDED.snapshot_version,
     zigzag_version = EXCLUDED.zigzag_version,
     size_bytes = EXCLUDED.size_bytes,
     metadata = EXCLUDED.metadata
RETURNING id, repo_id, job_id, branch, commit_sha, gcs_path,
    snapshot_version, zigzag_version, size_bytes, metadata,
    created_at
`

type InsertCLISnapshotParams struct {
	RepoID          pgtype.UUID
	Branch          string
	CommitSha       string
	GcsPath         string
	SnapshotVersion int32
	ZigzagVersion   string
	SizeBytes       int64
	Metadata        []byte
}

type InsertCLISnapshotRow struct {
	ID              pgtype.UUID
	RepoID          pgtype.UUID
	JobID           pgtype.UUID
	Branch          string
	CommitSha       string
	GcsPath         string
	SnapshotVersion int32
	ZigzagVersion   string
	SizeBytes       int64
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertCLISnapshot(ctx context.Context, arg InsertCLISnapshotParams) (InsertCLISnapshotRow, error) {
	row := q.db.QueryRow(ctx, insertCLISnapshot,
		arg.RepoID,
		arg.Branch,
		arg.CommitSha,
		arg.GcsPath,
		arg.SnapshotVersion,
		arg.ZigzagVersion,
		arg.SizeBytes,
		arg.Metadata,
	)
	var i InsertCLISnapshotRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.JobID,
		&i.Branch,
		&i.CommitSha,
		&i.GcsPath,
		&i.SnapshotVersion,
		&i.ZigzagVersion,
		&i.SizeBytes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertSnapshot = `-- name: InsertSnapshot :one
INSERT INTO snapshots (repo_id, job_id, branch, commit_sha, gcs_path, snapshot_version, zigzag_version, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, repo_id, job_id, branch, commit_sha, gcs_path, snapshot_version, zigzag_version, size_bytes, created_at, metadata
`

type InsertSnapshotParams struct {
	RepoID          pgtype.UUID
	JobID           pgtype.UUID
	Branch          string
	CommitSha       string
	GcsPath         string
	SnapshotVersion int32
	ZigzagVersion   string
	SizeBytes       int64
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRow(ctx, insertSnapshot,
		arg.RepoID,
		arg.JobID,
		arg.Branch,
		arg.CommitSha,
		arg.GcsPath,
		arg.SnapshotVersion,
		arg.ZigzagVersion,
		arg.SizeBytes,
	)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.JobID,
		&i.Branch,
		&i.CommitSha,
		&i.GcsPath,
		&i.SnapshotVersion,
		&i.ZigzagVersion,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Metadata,
	)
	return i, err
}
