// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: failed_logins.sql

package authstore

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentFailedLogins = `-- name: CountRecentFailedLogins :one
SELECT count(*) FROM failed_login_attempts
WHERE identifier = $1 AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentFailedLogins(ctx context.Context, identifier string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedLogins, identifier)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentFailedLoginsByIP = `-- name: CountRecentFailedLoginsByIP :one
SELECT count(*) FROM failed_login_attempts
WHERE ip_address = $1 AND created_at > now() - interval '15 minutes'
`

func (q *Queries) CountRecentFailedLoginsByIP(ctx context.Context, ipAddress netip.Addr) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentFailedLoginsByIP, ipAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldFailedLogins = `-- name: DeleteOldFailedLogins :exec
DELETE FROM failed_login_attempts WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) DeleteOldFailedLogins(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldFailedLogins)
	return err
}

const recordFailedLogin = `-- name: RecordFailedLogin :exec
INSERT INTO failed_login_attempts (identifier, ip_address, user_agent)
VALUES ($1, $2, $3)
`

type RecordFailedLoginParams struct {
	Identifier string
	IpAddress  netip.Addr
	UserAgent  pgtype.Text
}

func (q *Queries) RecordFailedLogin(ctx context.Context, arg RecordFailedLoginParams) error {
	_, err := q.db.Exec(ctx, recordFailedLogin, arg.Identifier, arg.IpAddress, arg.UserAgent)
	return err
}
