// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvite = `-- name: AcceptInvite :one
UPDATE invites
SET status = 'accepted', accepted_at = now()
WHERE id = $1 AND status = 'pending' AND expires_at > now()
RETURNING id, org_id, team_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, created_at
`

func (q *Queries) AcceptInvite(ctx context.Context, id pgtype.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, acceptInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (org_id, team_id, invited_by, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, team_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, created_at
`

type CreateInviteParams struct {
	OrgID     pgtype.UUID
	TeamID    pgtype.UUID
	InvitedBy pgtype.UUID
	Email     string
	Role      string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.OrgID,
		arg.TeamID,
		arg.InvitedBy,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
UPDATE invites SET status = 'expired'
WHERE status = 'pending' AND expires_at < now()
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvites)
	return err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT id, org_id, team_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, created_at FROM invites WHERE id = $1
`

func (q *Queries) GetInviteByID(ctx context.Context, id pgtype.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT id, org_id, team_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, created_at FROM invites
WHERE token_hash = $1 AND status = 'pending' AND expires_at > now()
`

func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TeamID,
		&i.InvitedBy,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOrgInvites = `-- name: ListOrgInvites :many
SELECT id, org_id, team_id, invited_by, email, role, token_hash, status, expires_at, accepted_at, created_at FROM invites
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrgInvites(ctx context.Context, orgID pgtype.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listOrgInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TeamID,
			&i.InvitedBy,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET status = 'revoked'
WHERE id = $1 AND org_id = $2 AND status = 'pending'
`

type RevokeInviteParams struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.OrgID)
	return err
}
