// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreateBackupCodesParams struct {
	UserID   pgtype.UUID
	CodeHash string
}

const deleteBackupCodes = `-- name: DeleteBackupCodes :exec
DELETE FROM mfa_backup_codes WHERE user_id = $1
`

func (q *Queries) DeleteBackupCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBackupCodes, userID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE mfa_settings
SET totp_enabled = false, totp_secret = NULL, totp_verified_at = NULL
WHERE user_id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, userID)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE mfa_settings
SET totp_enabled = true, totp_verified_at = now()
WHERE user_id = $1
`

func (q *Queries) EnableTOTP(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, enableTOTP, userID)
	return err
}

const getMFASettings = `-- name: GetMFASettings :one
SELECT id, user_id, totp_secret, totp_enabled, totp_verified_at, created_at, updated_at FROM mfa_settings WHERE user_id = $1
`

func (q *Queries) GetMFASettings(ctx context.Context, userID pgtype.UUID) (MfaSetting, error) {
	row := q.db.QueryRow(ctx, getMFASettings, userID)
	var i MfaSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnusedBackupCodes = `-- name: ListUnusedBackupCodes :many
SELECT id, user_id, code_hash, used_at, created_at FROM mfa_backup_codes
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) ListUnusedBackupCodes(ctx context.Context, userID pgtype.UUID) ([]MfaBackupCode, error) {
	rows, err := q.db.Query(ctx, listUnusedBackupCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaBackupCode
	for rows.Next() {
		var i MfaBackupCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE mfa_backup_codes SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}

const upsertMFASettings = `-- name: UpsertMFASettings :one
INSERT INTO mfa_settings (user_id, totp_secret, totp_enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET totp_secret = $2, totp_enabled = $3
RETURNING id, user_id, totp_secret, totp_enabled, totp_verified_at, created_at, updated_at
`

type UpsertMFASettingsParams struct {
	UserID      pgtype.UUID
	TotpSecret  []byte
	TotpEnabled bool
}

func (q *Queries) UpsertMFASettings(ctx context.Context, arg UpsertMFASettingsParams) (MfaSetting, error) {
	row := q.db.QueryRow(ctx, upsertMFASettings, arg.UserID, arg.TotpSecret, arg.TotpEnabled)
	var i MfaSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
