// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authstore

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	TargetType pgtype.Text
	TargetID   pgtype.UUID
	IpAddress  *netip.Addr
	UserAgent  pgtype.Text
	Metadata   []byte
	CreatedAt  pgtype.Timestamptz
}

type FailedLoginAttempt struct {
	ID         pgtype.UUID
	Identifier string
	IpAddress  netip.Addr
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Invite struct {
	ID         pgtype.UUID
	OrgID      pgtype.UUID
	TeamID     pgtype.UUID
	InvitedBy  pgtype.UUID
	Email      string
	Role       string
	TokenHash  string
	Status     string
	ExpiresAt  pgtype.Timestamptz
	AcceptedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type MfaBackupCode struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type MfaSetting struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	TotpSecret     []byte
	TotpEnabled    bool
	TotpVerifiedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OauthIdentity struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderID     string
	Email          pgtype.Text
	DisplayName    pgtype.Text
	AvatarUrl      pgtype.Text
	AccessToken    []byte
	RefreshToken   []byte
	TokenExpiresAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OauthState struct {
	ID          pgtype.UUID
	State       string
	Provider    string
	RedirectUri string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type OrgMembership struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Organization struct {
	ID           pgtype.UUID
	Slug         string
	Name         string
	LogoUrl      pgtype.Text
	Plan         string
	BillingEmail pgtype.Text
	MaxMembers   int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	SessionID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	IpAddress         *netip.Addr
	UserAgent         pgtype.Text
	DeviceName        pgtype.Text
	DeviceFingerprint pgtype.Text
	Country           pgtype.Text
	LastActiveAt      pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

type Team struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Slug        string
	Name        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type TeamMembership struct {
	ID        pgtype.UUID
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID                pgtype.UUID
	Email             string
	EmailVerified     bool
	FirstName         pgtype.Text
	LastName          pgtype.Text
	Nickname          pgtype.Text
	Bio               pgtype.Text
	Country           pgtype.Text
	Age               pgtype.Int4
	Timezone          string
	Language          string
	AvatarUrl         pgtype.Text
	PhoneCipher       []byte
	SocialLinks       []byte
	ProfileVisibility string
	OnboardingStep    string
	IsPlatformAdmin   bool
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID             pgtype.UUID
	SubscriptionID pgtype.UUID
	Event          string
	Payload        []byte
	ResponseStatus pgtype.Int4
	ResponseBody   pgtype.Text
	DeliveredAt    pgtype.Timestamptz
	Attempts       int32
	NextRetryAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type WebhookSubscription struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	Url       string
	Secret    string
	Events    []string
	Active    bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
