// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identities.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOAuthIdentitiesByUser = `-- name: CountOAuthIdentitiesByUser :one
SELECT count(*) FROM oauth_identities WHERE user_id = $1
`

func (q *Queries) CountOAuthIdentitiesByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthIdentitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_id, email, display_name, avatar_url, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, provider, provider_id, email, display_name, avatar_url, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateOAuthIdentityParams struct {
	UserID         pgtype.UUID
	Provider       string
	ProviderID     string
	Email          pgtype.Text
	DisplayName    pgtype.Text
	AvatarUrl      pgtype.Text
	AccessToken    []byte
	RefreshToken   []byte
	TokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :exec
DELETE FROM oauth_identities WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthIdentityParams struct {
	UserID   pgtype.UUID
	Provider string
}

func (q *Queries) DeleteOAuthIdentity(ctx context.Context, arg DeleteOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentity, arg.UserID, arg.Provider)
	return err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_id, email, display_name, avatar_url, access_token, refresh_token, token_expires_at, created_at, updated_at FROM oauth_identities
WHERE provider = $1 AND provider_id = $2
`

type GetOAuthIdentityParams struct {
	Provider   string
	ProviderID string
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOAuthIdentitiesByUser = `-- name: ListOAuthIdentitiesByUser :many
SELECT id, user_id, provider, provider_id, email, display_name, avatar_url, access_token, refresh_token, token_expires_at, created_at, updated_at FROM oauth_identities WHERE user_id = $1 ORDER BY provider
`

func (q *Queries) ListOAuthIdentitiesByUser(ctx context.Context, userID pgtype.UUID) ([]OauthIdentity, error) {
	rows, err := q.db.Query(ctx, listOAuthIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthIdentity
	for rows.Next() {
		var i OauthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthTokens = `-- name: UpdateOAuthTokens :exec
UPDATE oauth_identities
SET access_token = $3, refresh_token = $4, token_expires_at = $5
WHERE provider = $1 AND provider_id = $2
`

type UpdateOAuthTokensParams struct {
	Provider       string
	ProviderID     string
	AccessToken    []byte
	RefreshToken   []byte
	TokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.db.Exec(ctx, updateOAuthTokens,
		arg.Provider,
		arg.ProviderID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}
