// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_states.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthState = `-- name: CreateOAuthState :exec
INSERT INTO oauth_states (state, provider, redirect_uri, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateOAuthStateParams struct {
	State       string
	Provider    string
	RedirectUri string
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.Provider,
		arg.RedirectUri,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredOAuthStates = `-- name: DeleteExpiredOAuthStates :exec
DELETE FROM oauth_states WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthStates)
	return err
}

const getAndDeleteOAuthState = `-- name: GetAndDeleteOAuthState :one
DELETE FROM oauth_states
WHERE state = $1 AND expires_at > now()
RETURNING id, state, provider, redirect_uri, expires_at, created_at
`

func (q *Queries) GetAndDeleteOAuthState(ctx context.Context, state string) (OauthState, error) {
	row := q.db.QueryRow(ctx, getAndDeleteOAuthState, state)
	var i OauthState
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.Provider,
		&i.RedirectUri,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
