// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrgMembers = `-- name: CountOrgMembers :one
SELECT count(*) FROM org_memberships WHERE org_id = $1
`

func (q *Queries) CountOrgMembers(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrgMembers, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizations = `-- name: CountOrganizations :one
SELECT count(*) FROM organizations
`

func (q *Queries) CountOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrgMembership = `-- name: CreateOrgMembership :one
INSERT INTO org_memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, org_id, user_id, role, created_at, updated_at
`

type CreateOrgMembershipParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, createOrgMembership, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (slug, name)
VALUES ($1, $2)
RETURNING id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at
`

type CreateOrganizationParams struct {
	Slug string
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Slug, arg.Name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Plan,
		&i.BillingEmail,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgMembership = `-- name: DeleteOrgMembership :exec
DELETE FROM org_memberships WHERE org_id = $1 AND user_id = $2
`

type DeleteOrgMembershipParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteOrgMembership(ctx context.Context, arg DeleteOrgMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteOrgMembership, arg.OrgID, arg.UserID)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrgMembership = `-- name: GetOrgMembership :one
SELECT id, org_id, user_id, role, created_at, updated_at FROM org_memberships
WHERE org_id = $1 AND user_id = $2
`

type GetOrgMembershipParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRow(ctx, getOrgMembership, arg.OrgID, arg.UserID)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Plan,
		&i.BillingEmail,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Plan,
		&i.BillingEmail,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.id, om.org_id, om.user_id, om.role, om.created_at, om.updated_at, u.email, u.first_name, u.last_name, u.avatar_url
FROM org_memberships om
JOIN users u ON om.user_id = u.id
WHERE om.org_id = $1
ORDER BY om.role, u.email
`

type ListOrgMembersRow struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID pgtype.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at FROM organizations
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.LogoUrl,
			&i.Plan,
			&i.BillingEmail,
			&i.MaxMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.slug, o.name, o.logo_url, o.plan, o.billing_email, o.max_members, o.created_at, o.updated_at FROM organizations o
JOIN org_memberships om ON o.id = om.org_id
WHERE om.user_id = $1
ORDER BY o.name
`

func (q *Queries) ListUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.LogoUrl,
			&i.Plan,
			&i.BillingEmail,
			&i.MaxMembers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :exec
UPDATE org_memberships SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateOrgMemberRoleParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, logo_url = $3, billing_email = $4
WHERE id = $1
RETURNING id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ID           pgtype.UUID
	Name         string
	LogoUrl      pgtype.Text
	BillingEmail pgtype.Text
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.BillingEmail,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Plan,
		&i.BillingEmail,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationPlan = `-- name: UpdateOrganizationPlan :one
UPDATE organizations
SET plan = $2, max_members = $3
WHERE id = $1
RETURNING id, slug, name, logo_url, plan, billing_email, max_members, created_at, updated_at
`

type UpdateOrganizationPlanParams struct {
	ID         pgtype.UUID
	Plan       string
	MaxMembers int32
}

func (q *Queries) UpdateOrganizationPlan(ctx context.Context, arg UpdateOrganizationPlanParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationPlan, arg.ID, arg.Plan, arg.MaxMembers)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.LogoUrl,
		&i.Plan,
		&i.BillingEmail,
		&i.MaxMembers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
