// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT count(*) FROM team_memberships WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, slug, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, slug, name, description, created_at, updated_at
`

type CreateTeamParams struct {
	OrgID       pgtype.UUID
	Slug        string
	Name        string
	Description pgtype.Text
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.Description,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeamMembership = `-- name: CreateTeamMembership :one
INSERT INTO team_memberships (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, created_at
`

type CreateTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createTeamMembership, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMembership = `-- name: DeleteTeamMembership :exec
DELETE FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteTeamMembership(ctx context.Context, arg DeleteTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMembership, arg.TeamID, arg.UserID)
	return err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, org_id, slug, name, description, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamMembership = `-- name: GetTeamMembership :one
SELECT id, team_id, user_id, role, created_at FROM team_memberships
WHERE team_id = $1 AND user_id = $2
`

type GetTeamMembershipParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getTeamMembership, arg.TeamID, arg.UserID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.created_at, u.email, u.first_name, u.last_name, u.avatar_url
FROM team_memberships tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
ORDER BY tm.role, u.email
`

type ListTeamMembersRow struct {
	ID        pgtype.UUID
	TeamID    pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	Email     string
	FirstName pgtype.Text
	LastName  pgtype.Text
	AvatarUrl pgtype.Text
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsByOrg = `-- name: ListTeamsByOrg :many
SELECT id, org_id, slug, name, description, created_at, updated_at FROM teams
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListTeamsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTeams = `-- name: ListUserTeams :many
SELECT t.id, t.org_id, t.slug, t.name, t.description, t.created_at, t.updated_at FROM teams t
JOIN team_memberships tm ON t.id = tm.team_id
WHERE tm.user_id = $1 AND t.org_id = $2
ORDER BY t.name
`

type ListUserTeamsParams struct {
	UserID pgtype.UUID
	OrgID  pgtype.UUID
}

func (q *Queries) ListUserTeams(ctx context.Context, arg ListUserTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listUserTeams, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2, slug = $3, description = $4
WHERE id = $1
RETURNING id, org_id, slug, name, description, created_at, updated_at
`

type UpdateTeamParams struct {
	ID          pgtype.UUID
	Name        string
	Slug        string
	Description pgtype.Text
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamMemberRole = `-- name: UpdateTeamMemberRole :exec
UPDATE team_memberships SET role = $3
WHERE team_id = $1 AND user_id = $2
`

type UpdateTeamMemberRoleParams struct {
	TeamID pgtype.UUID
	UserID pgtype.UUID
	Role   string
}

func (q *Queries) UpdateTeamMemberRole(ctx context.Context, arg UpdateTeamMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberRole, arg.TeamID, arg.UserID, arg.Role)
	return err
}
