// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_verified, first_name, last_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, email_verified, first_name, last_name, nickname, bio, country, age, timezone, language, avatar_url, phone_cipher, social_links, profile_visibility, onboarding_step, is_platform_admin, created_at, updated_at
`

type CreateUserParams struct {
	Email         string
	EmailVerified bool
	FirstName     pgtype.Text
	LastName      pgtype.Text
	AvatarUrl     pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Bio,
		&i.Country,
		&i.Age,
		&i.Timezone,
		&i.Language,
		&i.AvatarUrl,
		&i.PhoneCipher,
		&i.SocialLinks,
		&i.ProfileVisibility,
		&i.OnboardingStep,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, first_name, last_name, nickname, bio, country, age, timezone, language, avatar_url, phone_cipher, social_links, profile_visibility, onboarding_step, is_platform_admin, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Bio,
		&i.Country,
		&i.Age,
		&i.Timezone,
		&i.Language,
		&i.AvatarUrl,
		&i.PhoneCipher,
		&i.SocialLinks,
		&i.ProfileVisibility,
		&i.OnboardingStep,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified, first_name, last_name, nickname, bio, country, age, timezone, language, avatar_url, phone_cipher, social_links, profile_visibility, onboarding_step, is_platform_admin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Bio,
		&i.Country,
		&i.Age,
		&i.Timezone,
		&i.Language,
		&i.AvatarUrl,
		&i.PhoneCipher,
		&i.SocialLinks,
		&i.ProfileVisibility,
		&i.OnboardingStep,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified, first_name, last_name, nickname, bio, country, age, timezone, language, avatar_url, phone_cipher, social_links, profile_visibility, onboarding_step, is_platform_admin, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.FirstName,
			&i.LastName,
			&i.Nickname,
			&i.Bio,
			&i.Country,
			&i.Age,
			&i.Timezone,
			&i.Language,
			&i.AvatarUrl,
			&i.PhoneCipher,
			&i.SocialLinks,
			&i.ProfileVisibility,
			&i.OnboardingStep,
			&i.IsPlatformAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_url = $2 WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID
	AvatarUrl pgtype.Text
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateUserOnboardingStep = `-- name: UpdateUserOnboardingStep :exec
UPDATE users SET onboarding_step = $2 WHERE id = $1
`

type UpdateUserOnboardingStepParams struct {
	ID             pgtype.UUID
	OnboardingStep string
}

func (q *Queries) UpdateUserOnboardingStep(ctx context.Context, arg UpdateUserOnboardingStepParams) error {
	_, err := q.db.Exec(ctx, updateUserOnboardingStep, arg.ID, arg.OnboardingStep)
	return err
}

const updateUserPhone = `-- name: UpdateUserPhone :exec
UPDATE users SET phone_cipher = $2 WHERE id = $1
`

type UpdateUserPhoneParams struct {
	ID          pgtype.UUID
	PhoneCipher []byte
}

func (q *Queries) UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) error {
	_, err := q.db.Exec(ctx, updateUserPhone, arg.ID, arg.PhoneCipher)
	return err
}

const updateUserPlatformAdmin = `-- name: UpdateUserPlatformAdmin :exec
UPDATE users SET is_platform_admin = $2 WHERE id = $1
`

type UpdateUserPlatformAdminParams struct {
	ID              pgtype.UUID
	IsPlatformAdmin bool
}

func (q *Queries) UpdateUserPlatformAdmin(ctx context.Context, arg UpdateUserPlatformAdminParams) error {
	_, err := q.db.Exec(ctx, updateUserPlatformAdmin, arg.ID, arg.IsPlatformAdmin)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET first_name = $2,
    last_name = $3,
    nickname = $4,
    bio = $5,
    country = $6,
    age = $7,
    timezone = $8,
    language = $9,
    social_links = $10,
    profile_visibility = $11
WHERE id = $1
RETURNING id, email, email_verified, first_name, last_name, nickname, bio, country, age, timezone, language, avatar_url, phone_cipher, social_links, profile_visibility, onboarding_step, is_platform_admin, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID                pgtype.UUID
	FirstName         pgtype.Text
	LastName          pgtype.Text
	Nickname          pgtype.Text
	Bio               pgtype.Text
	Country           pgtype.Text
	Age               pgtype.Int4
	Timezone          string
	Language          string
	SocialLinks       []byte
	ProfileVisibility string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Nickname,
		arg.Bio,
		arg.Country,
		arg.Age,
		arg.Timezone,
		arg.Language,
		arg.SocialLinks,
		arg.ProfileVisibility,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Bio,
		&i.Country,
		&i.Age,
		&i.Timezone,
		&i.Language,
		&i.AvatarUrl,
		&i.PhoneCipher,
		&i.SocialLinks,
		&i.ProfileVisibility,
		&i.OnboardingStep,
		&i.IsPlatformAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
