// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package authstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (subscription_id, event, payload, attempts, next_retry_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subscription_id, event, payload, response_status, response_body, delivered_at, attempts, next_retry_at, created_at
`

type CreateWebhookDeliveryParams struct {
	SubscriptionID pgtype.UUID
	Event          string
	Payload        []byte
	Attempts       int32
	NextRetryAt    pgtype.Timestamptz
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.SubscriptionID,
		arg.Event,
		arg.Payload,
		arg.Attempts,
		arg.NextRetryAt,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Event,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.DeliveredAt,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscriptions (org_id, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, url, secret, events, active, created_at, updated_at
`

type CreateWebhookSubscriptionParams struct {
	OrgID  pgtype.UUID
	Url    string
	Secret string
	Events []string
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.OrgID,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :exec
DELETE FROM webhook_subscriptions WHERE id = $1
`

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhookSubscription, id)
	return err
}

const getWebhookSubscription = `-- name: GetWebhookSubscription :one
SELECT id, org_id, url, secret, events, active, created_at, updated_at FROM webhook_subscriptions WHERE id = $1
`

func (q *Queries) GetWebhookSubscription(ctx context.Context, id pgtype.UUID) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscription, id)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWebhooksByEvent = `-- name: ListActiveWebhooksByEvent :many
SELECT id, org_id, url, secret, events, active, created_at, updated_at FROM webhook_subscriptions
WHERE org_id = $1 AND active = true AND $2 = ANY(events)
`

type ListActiveWebhooksByEventParams struct {
	OrgID  pgtype.UUID
	Events []string
}

func (q *Queries) ListActiveWebhooksByEvent(ctx context.Context, arg ListActiveWebhooksByEventParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listActiveWebhooksByEvent, arg.OrgID, arg.Events)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookSubscription
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, subscription_id, event, payload, response_status, response_body, delivered_at, attempts, next_retry_at, created_at FROM webhook_deliveries
WHERE delivered_at IS NULL AND (next_retry_at IS NULL OR next_retry_at <= now())
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.Event,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.DeliveredAt,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, subscription_id, event, payload, response_status, response_body, delivered_at, attempts, next_retry_at, created_at FROM webhook_deliveries
WHERE subscription_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	SubscriptionID pgtype.UUID
	Limit          int32
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.SubscriptionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.Event,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.DeliveredAt,
			&i.Attempts,
			&i.NextRetryAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, org_id, url, secret, events, active, created_at, updated_at FROM webhook_subscriptions
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, orgID pgtype.UUID) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookSubscription
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDeliveryResult = `-- name: UpdateWebhookDeliveryResult :exec
UPDATE webhook_deliveries
SET response_status = $2, response_body = $3, delivered_at = $4, attempts = $5, next_retry_at = $6
WHERE id = $1
`

type UpdateWebhookDeliveryResultParams struct {
	ID             pgtype.UUID
	ResponseStatus pgtype.Int4
	ResponseBody   pgtype.Text
	DeliveredAt    pgtype.Timestamptz
	Attempts       int32
	NextRetryAt    pgtype.Timestamptz
}

func (q *Queries) UpdateWebhookDeliveryResult(ctx context.Context, arg UpdateWebhookDeliveryResultParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDeliveryResult,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.DeliveredAt,
		arg.Attempts,
		arg.NextRetryAt,
	)
	return err
}

const updateWebhookSubscription = `-- name: UpdateWebhookSubscription :one
UPDATE webhook_subscriptions
SET url = $2, events = $3, active = $4
WHERE id = $1
RETURNING id, org_id, url, secret, events, active, created_at, updated_at
`

type UpdateWebhookSubscriptionParams struct {
	ID     pgtype.UUID
	Url    string
	Events []string
	Active bool
}

func (q *Queries) UpdateWebhookSubscription(ctx context.Context, arg UpdateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, updateWebhookSubscription,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.Active,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
